Update archive.yml

diff --git a/.github/workflows/archive.yml b/.github/workflows/archive.yml
--- a/.github/workflows/archive.yml
+++ b/.github/workflows/archive.yml
@@ -29,6 +29,13 @@ jobs:
           pip install internetarchive tubeup==0.0.33 snscrape gallery-dl instaup yt-dlp
           mkdir -p ~/.tubeup          
           # playwright install firefox
+      - uses: actions/checkout@master
+      - name: rclone
+        uses: wei/rclone@v1
+        env:
+          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
+        with:
+          args: help
       - uses: actions/cache@v3
         id: cache
         with:
@@ -48,6 +55,7 @@ jobs:
           # instaloader :stories --login themariocrafter 
           # zip -r stories.zip ":stories" 
           # ia upload instagramstories20230216 stories.zip --retries 100          
+          rclone copy :http,url='http://s1.bitdl.ir/Software/HandHeld/': internetarchive:handheldsoftwarecollection
           mkdir ~/.instaup
           echo '${{ secrets.INSTA3 }}' | base64 --decode > /home/runner/.instaup/themariocrafter.login
           tubeup --get-comments https://youtube.com/playlist?list=PLuqy83wG7WekC77bSbvE1VWDDiNRxOAG_
@@ -60,15 +68,15 @@ jobs:
           # tubeup --get-comments "twitch.tv/ninja_muffin99/videos?filter=all"    
           #tubeup --get-comments --debug https://youtube.com/@Gygos3654         
           # tubeup https://www.dropbox.com/s/cfgepq38fzr0foz/MOV_0100.mp4?dl=0 --get-comments
-          # tubeup http://download.samygo.tv/Others/hidden/SamyGO-VM.7z https://drive.google.com/file/d/1c8D8-KxsISBVQqRh6AvmM5noNeXqdCtq/view?usp=drivesdk https://drive.google.com/file/d/1S9ue_WIfCnrHr2VTh2RK8NOcO-NJA5tx/view?usp=drivesdk  --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments                  
-          yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/@${{ matrix.channel }}/channels" | jq -r ".entries[] | select(.upload_date < \"20160101\") | .webpage_url" > result.log
-          while IFS="" read -r p || [ -n "$p" ]
-           do
-            if ! tubeup "$p" --debug --get-comments --use-download-archive || true
-            then
-              echo "Failed to archive $p"
-              continue
-            fi
+          # tubeup http://download.samygo.tv/Others/hidden/SamyGO-VM.7z https://drive.google.com/file/d/1c8D8-KxsISBVQqRh6AvmM5noNeXqdCtq/view?usp=drivesdk https://drive.google.com/file/d/1S9ue_WIfCnrHr2VTh2RK8NOcO-NJA5tx/view?usp=drivesdk  --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments                        
+          # yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/@${{ matrix.channel }}/channels" | jq -r ".entries[] | select(.upload_date < \"20160101\") | .webpage_url" > result.log
+          # while IFS="" read -r p || [ -n "$p" ]
+          #  do
+          #   if ! tubeup "$p" --debug --get-comments --use-download-archive || true
+          #   then
+          #     echo "Failed to archive $p"
+          #     continue
+          #   fi
            done < result.log
       - name: Get sha1 of .ytdlarchive
         id: sha1
