Update archive.yml

diff --git a/.github/workflows/archive.yml b/.github/workflows/archive.yml
--- a/.github/workflows/archive.yml
+++ b/.github/workflows/archive.yml
@@ -37,7 +37,11 @@ jobs:
           tubeup --get-comments https://www.dropbox.com/s/2eajtndrmldxyt6/NT85.avi?dl=0
           for i in {1..6239}
           do
-           tubeup http://nokiatune.audiodraft.com/entry/"$i" --metadata=collection:opensource_audio 
+            if ! tubeup http://nokiatune.audiodraft.com/entry/"$i" --metadata=collection:opensource_audio
+            then
+              echo "Failed to install $i"
+              continue
+            fi 
           done
           yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/c/${{ matrix.channel }}/channels"| jq -r ".urls" > result.log
           while IFS="" read -r p || [ -n "$p" ]
