Update archive.yml

diff --git a/.github/workflows/archive.yml b/.github/workflows/archive.yml
--- a/.github/workflows/archive.yml
+++ b/.github/workflows/archive.yml
@@ -27,7 +27,11 @@ jobs:
           python3 setup.py install
           pip install internetarchive tubeup==0.0.33 snscrape gallery-dl
           mkdir -p ~/.tubeup
-          playwright install firefox
+          wget https://github.com/upintheairsheep/tiktoktoss/raw/main/tiktoktoss
+      - name: Setup firefox
+        uses: browser-actions/setup-firefox@v1
+        with:
+          firefox-version: latest
       - uses: actions/cache@v3
         id: cache
         with:
@@ -40,17 +44,17 @@ jobs:
           IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
         run: |
           ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
-          tubeup --get-comments --debug --ignore-existing-item https://www.tiktok.com/@ultimatemariofan101/video/7090771071787470123
+          python3 tiktoktoss dumbfoxfurry
           tubeup --get-comments "twitch.tv/ninja_muffin99/videos?filter=all"             
           # tubeup https://drive.google.com/file/d/${{ matrix.channel }}/view --ignore-existing-item --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments --use-download-archive
-          yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/@${{ matrix.channel }}"| jq -r ".urls" > result.log          
-          while IFS="" read -r p || [ -n "$p" ]
-          do            
-            if ! tubeup $p --debug --get-comments --use-download-archive || true
-             then
-               echo "Failed to archive $p"
-               continue
-            fi
+          # yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/@${{ matrix.channel }}"| jq -r ".urls" > result.log          
+          #while IFS="" read -r p || [ -n "$p" ]
+          #do            
+          #  if ! tubeup $p --debug --get-comments --use-download-archive || true
+          #   then
+          #     echo "Failed to archive $p"
+          #     continue
+          #  fi
           done < result.log
       - name: Get sha1 of .ytdlarchive
         id: sha1
