Update archive.yml

diff --git a/.github/workflows/archive.yml b/.github/workflows/archive.yml
--- a/.github/workflows/archive.yml
+++ b/.github/workflows/archive.yml
@@ -42,15 +42,18 @@ jobs:
         run: |
           ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
           # tubeup "https://tiktok.com/@newlinersseries"  --get-comments
-          yt-dlp -j --no-warnings -i --flat-playlist "https://tiktok.com/@${{ matrix.channel }}" | jq -r ".urls"  > result.log
-          while IFS="" read -r p || [ -n "$p" ]
-            do
-             if ! tubeup "$p" --debug --get-comments --use-download-archive || true
-             then
-               echo "Failed to archive $p"
-               continue
-             fi
-            done < result.log
+          yt-dlp -j --no-warnings -i --flat-playlist "https://tiktok.com/@newlinersseries" | jq -r ".urls" > result.log
+          
+          while IFS="" read -r p || [ -n "$p" ]; do
+              if [ -z "$p" ]; then
+                  echo "Empty URL found"
+                  continue
+              fi
+          
+              if ! tubeup "$p" --debug --get-comments --use-download-archive || true; then
+                  echo "Failed to archive $p"
+              fi
+          done < result.log
       - name: Get sha1 of .ytdlarchive
         id: sha1
         run: |
